version: 2

sphinx:
  builder: pydoctor
  fail_on_warning: true

formats:
  - pdf
  - epub

python:
  version: 3.8
  system_packages: False
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
