# CircleCI 2.0 configuration file for running Twisted checks.
#
# Email notifications are configured only from web.
# See "Email Preferences by Organization" in
# https://circleci.com/account/notifications
#
# Based on these v1.0 steps:
# https://pewpewthespells.com/blog/building_python_on_circleci.html
#
# This uses the v2 workflows and a separate commit status is sent for each
# job.
#
# CircleCI 2.0 automatically sets a $BASH_ENV variable to a
# random name in /tmp, and will source this file for each step.
#
version: 2

aliases:
  - &preparation_run_group
    run:
      name: Prepare the virtualenv.
      command: |
        "$PYTHON" --version
        "$PYTHON" -m pip --version
        "$PYTHON" -m venv venv
        venv/bin/pip install -U pip
        venv/bin/python -m pip install tox
        venv/bin/python -m pip freeze
        venv/bin/python --version

jobs:
  no-op:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - run:
          name: No-op
          command: |
            echo

workflows:
  version: 2
  all-tests:
    jobs:
      - no-op
